// wxl-sign: offline keygen + manifest signer for the WarcraftXL extension trust gate.
// Copyright (C) 2026 WarcraftXL
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

#include "engine/security/Crypto.hpp"

#include "common/Log.hpp"

#include <windows.h>

// LUAJIT_VERSION binds a manifest to the exact bytecode ABI it was signed against. luajit.h is the
// generated LuaJIT build header; the tool's include path adds ${WXL_LJ_BUILD}/src.
extern "C"
{
#include "luajit.h"
}

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace
{
    constexpr char kDefaultKeyFile[]   = "wxl-signing-key.bin";
    constexpr char kDefaultHeaderPath[] = "src/engine/security/PublicKey.hpp";

    /// Reads an entire file into a byte buffer. Returns false (empty out) on any error.
    bool ReadAll(const std::string& path, std::vector<uint8_t>& out)
    {
        FILE* f = nullptr;
        if (fopen_s(&f, path.c_str(), "rb") != 0 || !f)
            return false;
        std::fseek(f, 0, SEEK_END);
        const long size = std::ftell(f);
        std::fseek(f, 0, SEEK_SET);
        if (size < 0)
        {
            std::fclose(f);
            return false;
        }
        out.resize(static_cast<size_t>(size));
        const bool ok = out.empty() || std::fread(out.data(), 1, out.size(), f) == out.size();
        std::fclose(f);
        if (!ok)
            out.clear();
        return ok;
    }

    /// Writes a byte buffer to a file in binary mode (no CRLF translation). Returns false on error.
    bool WriteAll(const std::string& path, const void* data, size_t len)
    {
        FILE* f = nullptr;
        if (fopen_s(&f, path.c_str(), "wb") != 0 || !f)
            return false;
        const bool ok = len == 0 || std::fwrite(data, 1, len, f) == len;
        return std::fclose(f) == 0 && ok;
    }

    /// Value that follows `--flag` in argv, or nullptr when the flag is absent or has no argument.
    const char* FindOption(int argc, char** argv, const char* flag)
    {
        for (int i = 0; i < argc - 1; ++i)
            if (std::strcmp(argv[i], flag) == 0)
                return argv[i + 1];
        return nullptr;
    }

    /// Recursively collects *.lua / *.out under baseDir, as forward-slashed paths relative to baseDir.
    void Enumerate(const std::string& baseDir, const std::string& rel, std::vector<std::string>& out)
    {
        const std::string dirOnDisk = rel.empty() ? baseDir : baseDir + "/" + rel;
        const std::string pattern   = dirOnDisk + "/*";

        WIN32_FIND_DATAA fd;
        HANDLE           h = FindFirstFileA(pattern.c_str(), &fd);
        if (h == INVALID_HANDLE_VALUE)
            return;
        do
        {
            const char* name = fd.cFileName;
            if (std::strcmp(name, ".") == 0 || std::strcmp(name, "..") == 0)
                continue;
            const std::string childRel = rel.empty() ? name : rel + "/" + name;
            if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)
            {
                Enumerate(baseDir, childRel, out);
                continue;
            }
            const char* dot = std::strrchr(name, '.');
            if (dot && (_stricmp(dot, ".lua") == 0 || _stricmp(dot, ".out") == 0))
                out.push_back(childRel);
        } while (FindNextFileA(h, &fd));
        FindClose(h);
    }

    /// Renders PublicKey.hpp with the real key baked in and kHasSigningKey flipped to true.
    std::string RenderPublicKeyHeader(const uint8_t pk[32])
    {
        std::string s;
        s += "// Embedded Ed25519 public key that authorises the extension manifest. GENERATED FILE.\n";
        s += "// Copyright (C) 2026 WarcraftXL. GPLv3 (regenerate with `wxl-sign keygen`; do not hand-edit).\n";
        s += "\n";
        s += "#pragma once\n\n";
        s += "#include <cstdint>\n\n";
        s += "/// The manifest-signing public key baked into the DLL. Generated by `wxl-sign keygen`; the\n";
        s += "/// matching secret key lives in wxl-signing-key.bin and MUST be kept out of version control.\n";
        s += "namespace wxl::security\n{\n";
        s += "    inline constexpr uint8_t kEd25519PublicKey[32] = {\n";
        for (int row = 0; row < 4; ++row)
        {
            s += "        ";
            for (int col = 0; col < 8; ++col)
            {
                char buf[8];
                std::snprintf(buf, sizeof(buf), "0x%02x,", pk[row * 8 + col]);
                s += buf;
                if (col != 7)
                    s += ' ';
            }
            s += '\n';
        }
        s += "    };\n\n";
        s += "    /// A real signing key is baked in, so production verification is active.\n";
        s += "    inline constexpr bool kHasSigningKey = true;\n";
        s += "}\n";
        return s;
    }

    int Usage()
    {
        WLOG_ERROR("usage:");
        WLOG_ERROR("  wxl-sign keygen [--out <PublicKey.hpp>] [--key <privkey.bin>]");
        WLOG_ERROR("  wxl-sign sign <extensions-dir> [--key <privkey.bin>]");
        return 2;
    }

    int DoKeygen(int argc, char** argv)
    {
        const char* headerPath = FindOption(argc, argv, "--out");
        const char* keyPath    = FindOption(argc, argv, "--key");
        const std::string header = headerPath ? headerPath : kDefaultHeaderPath;
        const std::string key    = keyPath ? keyPath : kDefaultKeyFile;

        uint8_t pk[32];
        uint8_t sk[64];
        wxl::security::GenerateKeypair(pk, sk);

        if (!WriteAll(key, sk, sizeof(sk)))
        {
            WLOG_ERROR("cannot write secret key '%s'", key.c_str());
            return 1;
        }
        const std::string headerText = RenderPublicKeyHeader(pk);
        if (!WriteAll(header, headerText.data(), headerText.size()))
        {
            WLOG_ERROR("cannot write public-key header '%s'", header.c_str());
            return 1;
        }

        WLOG_INFO("public key: %s", wxl::security::ToHex(pk, 32).c_str());
        WLOG_INFO("secret key written to '%s' -- KEEP IT SECRET and OUT of git", key.c_str());
        WLOG_INFO("public key baked into '%s' (kHasSigningKey = true)", header.c_str());
        return 0;
    }

    int DoSign(int argc, char** argv)
    {
        if (argc < 3 || argv[2][0] == '-')
        {
            WLOG_ERROR("sign requires an <extensions-dir>");
            return Usage();
        }
        std::string dir = argv[2];
        while (!dir.empty() && (dir.back() == '/' || dir.back() == '\\'))
            dir.pop_back();

        const char*       keyPath = FindOption(argc, argv, "--key");
        const std::string key     = keyPath ? keyPath : kDefaultKeyFile;

        std::vector<uint8_t> sk;
        if (!ReadAll(key, sk) || sk.size() != 64)
        {
            WLOG_ERROR("cannot read 64-byte secret key '%s'", key.c_str());
            return 1;
        }

        std::vector<std::string> rels;
        Enumerate(dir, "", rels);
        std::sort(rels.begin(), rels.end());

        // Build the manifest text with LF endings, then sign the exact bytes. The format here MUST be
        // byte-identical to what engine/security/Manifest.cpp parses and verifies.
        std::string manifest = "wxl-manifest 1\n";
        manifest += "luajit ";
        manifest += LUAJIT_VERSION;
        manifest += "\n";
        for (const std::string& rel : rels)
        {
            std::vector<uint8_t> bytes;
            if (!ReadAll(dir + "/" + rel, bytes))
            {
                WLOG_ERROR("cannot read extension '%s'", rel.c_str());
                return 1;
            }
            const std::array<uint8_t, 64> hash = wxl::security::Sha512(bytes.data(), bytes.size());
            manifest += wxl::security::ToHex(hash.data(), 64);
            manifest += ' ';
            manifest += rel;
            manifest += '\n';
        }

        uint8_t sig[64];
        wxl::security::SignDetached(sk.data(), manifest.data(), manifest.size(), sig);
        const std::string sigHex = wxl::security::ToHex(sig, 64);

        if (!WriteAll(dir + "/manifest", manifest.data(), manifest.size()))
        {
            WLOG_ERROR("cannot write '%s/manifest'", dir.c_str());
            return 1;
        }
        if (!WriteAll(dir + "/manifest.sig", sigHex.data(), sigHex.size()))
        {
            WLOG_ERROR("cannot write '%s/manifest.sig'", dir.c_str());
            return 1;
        }

        WLOG_INFO("signed %zu extension(s) in '%s' for %s", rels.size(), dir.c_str(), LUAJIT_VERSION);
        WLOG_INFO("wrote manifest + manifest.sig");
        return 0;
    }
}

/**
 * @brief Entry point: dispatches `keygen` or `sign`.
 * @param argc  argument count.
 * @param argv  argument values.
 * @return 0 on success, non-zero on failure or bad usage.
 */
int main(int argc, char** argv)
{
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    wxl::log::EnableConsole("[wxl-sign] ");

    if (argc < 2)
        return Usage();
    if (std::strcmp(argv[1], "keygen") == 0)
        return DoKeygen(argc, argv);
    if (std::strcmp(argv[1], "sign") == 0)
        return DoSign(argc, argv);
    return Usage();
}
