// Embedded Ed25519 public key that authorises the extension manifest. GENERATED FILE.
// Copyright (C) 2026 WarcraftXL. GPLv3 (regenerate with `wxl-sign keygen`; do not hand-edit).

#pragma once

#include <cstdint>

/// The manifest-signing public key baked into the DLL. Generated by `wxl-sign keygen`; the
/// matching secret key lives in wxl-signing-key.bin and MUST be kept out of version control.
namespace wxl::security
{
    inline constexpr uint8_t kEd25519PublicKey[32] = {
        0x6a, 0xc5, 0x0e, 0xd8, 0xef, 0x98, 0x89, 0x5a,
        0x41, 0x26, 0x9d, 0x4a, 0x6b, 0x18, 0x5b, 0xfd,
        0x8c, 0xa6, 0x01, 0x58, 0xc4, 0x4f, 0x23, 0xad,
        0x0d, 0x43, 0xeb, 0xa6, 0x18, 0x30, 0x47, 0xd9,
    };

    /// A real signing key is baked in, so production verification is active.
    inline constexpr bool kHasSigningKey = true;
}
